apps/libreria/urls.py
from django.urls import path
from .views import (
    BookListView,
    BookDetailView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
    BookCrudListView,
    AuthorListView,
    AuthorCreateView,
    AuthorUpdateView,
    AuthorDeleteView,
    AuthorCrudListView,
    author_detail,
    GenreCreateView,
    genero_detail,
    GenreUpdateView,
    GenreDeleteView,
    GenreCrudListView,
    search_books,
)

app_name = "libreria"

urlpatterns = [
    # URLs libros
    path("", BookListView.as_view(), name="book-list"),
    path("create/", BookCreateView.as_view(), name="create"),
    path("<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("<int:pk>/edit/", BookUpdateView.as_view(), name="book-update"),
    path("<int:pk>/delete/", BookDeleteView.as_view(), name="book-delete"),
    path("crud/", BookCrudListView.as_view(), name="book-crud"),
    path("search/", search_books, name="search-book"),
    # URLs autores
    path("author/", AuthorListView.as_view(), name="author-list"),
    path("author/create/", AuthorCreateView.as_view(), name="author-create"),
    path("author/<int:pk>/", author_detail, name="author-detail"),
    path("author/<int:pk>/edit/", AuthorUpdateView.as_view(), name="author-update"),
    path("author/<int:pk>/delete/", AuthorDeleteView.as_view(), name="author-delete"),
    path("author/crud/", AuthorCrudListView.as_view(), name="author-crud"),
    # URLs generos
    path("genre/create/", GenreCreateView.as_view(), name="genre-create"),
    path("genre/<int:pk>/", genero_detail, name="genre-detail"),
    path("genre/<int:pk>/edit/", GenreUpdateView.as_view(), name="genre-update"),
    path("genre/<int:pk>/delete/", GenreDeleteView.as_view(), name="genre-delete"),
    path("genre/crud/", GenreCrudListView.as_view(), name="genre-crud"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.libreria.views import home, AboutView

urlpatterns = (
    [
        # Django admin
        path("admin/", admin.site.urls),
        # Usuarios
        path("accounts/", include("django.contrib.auth.urls")),
        # Apps locales
        path("accounts/", include("apps.accounts.urls")),
        path("", home, name="index"),
        path("books/", include("apps.libreria.urls")),
        path("about/", AboutView.as_view(), name="about"),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

apps/libreria/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    title = models.CharField("Título", max_length=50)
    editorial = models.CharField("Editorial", max_length=50, null=True, blank=True)
    isbn = models.CharField("ISBN", max_length=13, null=True, blank=True)
    price = models.FloatField("Precio")
    language = models.ForeignKey(
        "Language", on_delete=models.SET_NULL, null=True, blank=True
    )
    genre = models.ManyToManyField("Genre", verbose_name="Género")
    author = models.ForeignKey(
        "Author",
        verbose_name="Autor",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="author_books",
    )
    image = models.ImageField(
        "Tapa del libro", upload_to="books/", null=True, blank=True
    )
    resumen = models.TextField("Reseña", max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Devuelve el URL de una instancia particular de un Libro
        """
        return reverse("libreria:book-detail", args=[self.id])

    class Meta:
        ordering = ["title", "editorial"]
        verbose_name = "Libro"
        verbose_name_plural = "Libros"


class Author(models.Model):
    first_name = models.CharField("Nombre", max_length=20, null=True, blank=True)
    last_name = models.CharField("Apellido", max_length=50)
    country = models.CharField(
        "Nacionalidad", max_length=50, null=True, blank=True, help_text="País de origen"
    )

    class Meta:
        ordering = ["last_name", "first_name"]
        verbose_name = "Autor"
        verbose_name_plural = "Autores"

    def fullname(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.fullname()

    def get_absolute_url(self):
        """
        Devuelve el URL de una instancia particular de un Libro
        """
        return reverse("libreria:author-detail", args=[self.id])


class Genre(models.Model):
    genre = models.CharField(
        "Género",
        max_length=100,
        help_text="Ingresa un género de libro (ej. Ciencia Ficción, Misterio)",
    )

    class Meta:
        verbose_name = "Género"
        verbose_name_plural = "Géneros"
        ordering = [
            "genre",
        ]

    def __str__(self):
        return self.genre

    def get_absolute_url(self):
        """
        Devuelve el URL de una instancia particular de un Género
        """
        return reverse("libreria:genre-detail", args=[self.id])


class Language(models.Model):
    language = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Idioma"
        verbose_name_plural = "Idiomas"

    def __str__(self):
        return self.language

    def get_absolute_url(self):
        """
        Devuelve el URL de una instancia particular de un Libro
        """
        return reverse("libreria:genre-detail", args=[self.id])

apps/libreria/forms.py
from django import forms
from .models import Book, Author, Genre, Language


class BookForm(forms.ModelForm):
    """Form para agregar y editar Books"""

    class Meta:
        model = Book
        fields = "__all__"


class AuthorForm(forms.ModelForm):
    """Form para agregar y editar autores"""

    class Meta:
        model = Author
        fields = "__all__"


class GenreForm(forms.ModelForm):
    """Form para agregar y editar generos literarios"""

    class Meta:
        model = Genre
        fields = "__all__"


class LanguageForm(forms.ModelForm):
    """Form para agregar y editar Languages"""

    class Meta:
        model = Language
        fields = "__all__"

apps/libreria/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)
from .models import Book, Author, Genre
from .forms import BookForm, AuthorForm, GenreForm, LanguageForm
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model

User = get_user_model()


def home(request):
    libros = Book.objects.all().order_by("-id")[:3]
    context = {"libros": libros}
    return render(request, "index.html", context=context)


class BookListView(ListView):
    """Vista para ver la lista de libros"""

    model = Book
    context_object_name = "libros"
    queryset = (
        Book.objects.all()
        .prefetch_related(
            "genre",
        )
        .select_related("author")
    )


class BookDetailView(LoginRequiredMixin, DetailView):
    """Vista para ver los detalles de una instancia de
    la clase Book"""

    model = Book
    context_object_name = "libro"


class BookCreateView(LoginRequiredMixin, CreateView):
    """Vista para agregar Libros"""

    model = Book
    form_class = BookForm
    template_name_suffix = "_create_form"
    success_url = reverse_lazy("libreria:book-crud")


class BookUpdateView(LoginRequiredMixin, UpdateView):
    """Vista para editar Libros"""

    model = Book
    form_class = BookForm
    template_name_suffix = "_edit_form"
    success_url = reverse_lazy("libreria:book-crud")


class BookDeleteView(LoginRequiredMixin, DeleteView):
    """Vista para borrar un libro"""

    model = Book
    context_object_name = "libro"
    success_url = reverse_lazy("libreria:book-crud")


class BookCrudListView(LoginRequiredMixin, ListView):
    model = Book
    context_object_name = "libros"
    template_name = "libreria/book_crud.html"
    queryset = (
        Book.objects.all()
        .prefetch_related(
            "genre",
        )
        .select_related("author")
    )


class AuthorListView(ListView):
    """Vista para ver la lista de autores"""

    model = Author
    context_object_name = "autores"


def author_detail(request, pk):
    """Detalle del Autor y listado de sus libros"""
    aviso = ""
    autor = get_object_or_404(Author, pk=pk)
    libros = Book.objects.filter(author=autor)
    if libros.count() == 0:
        aviso = "No hay libros de este autor."
    context = {
        "autor": autor,
        "libros": libros,
        "aviso": aviso,
    }
    print(libros)
    return render(request, "libreria/author_detail.html", context)


class AuthorCreateView(LoginRequiredMixin, CreateView):
    """Vista para agregar Autores"""

    model = Author
    form_class = AuthorForm
    template_name_suffix = "_create_form"
    success_url = reverse_lazy("libreria:author-crud")


class AuthorUpdateView(LoginRequiredMixin, UpdateView):
    """Vista para editar Autores"""

    model = Author
    form_class = AuthorForm
    template_name_suffix = "_edit_form"
    success_url = reverse_lazy("libreria:author-crud")


class AuthorDeleteView(LoginRequiredMixin, DeleteView):
    """Vista para borrar un Autor"""

    model = Author
    context_object_name = "autor"
    success_url = reverse_lazy("libreria:author-crud")


class AuthorCrudListView(LoginRequiredMixin, ListView):
    model = Author
    context_object_name = "autores"
    template_name = "libreria/author_crud.html"


def genero_detail(request, pk):
    """Detalle del Género"""
    genero = get_object_or_404(Genre, pk=pk)
    libros = Book.objects.filter(genre=genero)
    cantidad = libros.count()
    context = {
        "genero": genero,
        "libros": libros,
        "cantidad": cantidad,
    }
    return render(request, "libreria/genre_detail.html", context)


class GenreCreateView(LoginRequiredMixin, CreateView):
    """Vista para agregar Géneros"""

    model = Genre
    form_class = GenreForm
    template_name_suffix = "_create_form"
    success_url = reverse_lazy("libreria:genre-crud")


class GenreUpdateView(LoginRequiredMixin, UpdateView):
    """Vista para editar Géneros"""

    model = Genre
    form_class = GenreForm
    template_name_suffix = "_edit_form"
    success_url = reverse_lazy("libreria:genre-crud")


class GenreDeleteView(LoginRequiredMixin, DeleteView):
    """Vista para borrar un Género"""

    model = Genre
    context_object_name = "genero"
    success_url = reverse_lazy("libreria:genre-crud")


class GenreCrudListView(LoginRequiredMixin, ListView):
    model = Genre
    context_object_name = "generos"
    template_name = "libreria/genre_crud.html"


def search_books(request):
    search = request.GET["search"]
    libros = Book.objects.filter(
        Q(title__icontains=search)
        # | Q(author__last_name__icontains=search)
        # | Q(genre__genre__icontains=search)
    )
    context = {"libros": libros, "search": search}
    print(context)
    return render(request, "libreria/book_search.html", context=context)

class AboutView(TemplateView):
    template_name = "about.html"

apps/libreria/templates/libreria/author_create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Agregar Autor
{% endblock title %}
{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-md-8 my-3">
                <h3 class="mb-3">Agregar autor</h3>
                {% if user.is_superuser %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-success">Agregar autor</button>
                        <a href="{% url 'libreria:author-crud' %}" class="btn btn-primary">Cancelar</a>
                    </form>
                {% else %}
                    <h2>No tienes permisos suficientes para ingresar a esta sección.</h2>
                    <a href="{% url 'libreria:author-list' %}" class="btn btn-primary">Volver</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/author_crud.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Lista de Libros
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <div class="row">
            <div class="col">
                <h1>Lista de libros</h1>
                {% if user.is_superuser %}
                    <div class="btn-group" role="group" aria-label="links">
                        <a href="{% url 'libreria:author-create' %}"
                           type="button"
                           class="btn btn-secondary">Agregar autor</a>
                    </div>
                {% endif %}
                <table class="table table-hover mt-3">
                    <thead>
                        <tr>
                            <th scope="col">#ID</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">Nombre completo</th>
                            <th scope="col">Pais origen</th>
                            <th scope="col" colspan="2" class="text-center">Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for autor in autores %}
                            <tr>
                                <th scope="row">{{ autor.id }}</th>
                                <td>{{ autor.first_name }}</td>
                                <td>{{ autor.last_name }}</td>
                                <td>
                                    <a href="{% url 'libreria:author-detail' pk=autor.pk %}">{{ autor.fullname }}</a>
                                </td>
                                <td>{{ autor.country }}</td>
                                <td>
                                    {% if user.is_staff %}
                                        <a href="{% url 'libreria:author-update' pk=autor.pk %}"
                                           class="btn btn-warning">Editar</a>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if user.is_superuser %}
                                        <a href="{% url 'libreria:author-delete' pk=autor.pk %}"
                                           class="btn btn-danger">Eliminar</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/author_detail.html
{% extends "base.html" %}
{% block title %}
    {{ autor.fullname }}
{% endblock title %}
{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-md-12">
                <h2>{{ autor.fullname }}</h2>
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h4 class="card-title">Acerca del autor</h4>
                                <p class="card-text">
                                    <b>Nombre:</b> {{ autor.first_name }}
                                </p>
                                <p class="card-text">
                                    <b>Apellido:</b> {{ autor.last_name }}
                                </p>
                                <p class="card-text">
                                    <b>Nacionalidad:</b> {{ autor.country }}
                                </p>
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-md-2">
                                <p class="card-text">
                                    <b> Biografia:</b>
                                </p>
                            </div>
                            <div class="col-md-10">{% lorem 50 w random %}.</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <h3>
                    {% if aviso %}{{ aviso }}{% endif %}
                </h3>
            </div>
        </div>
        <div class="row">
            {% for libro in libros %}
                <div class="col-md-4">
                    <div class="card my-3">
                        <img src="{{ libro.image.url }}"
                             class="card-img-top"
                             alt="{{ libro.title }}"
                             height="400px"
                             width="auto"/>
                        <div class="card-body">
                            <h5 class="card-title">{{ libro.title }}</h5>
                            <h6 class="card-text">{{ libro.author }}</h6>
                            <p class="card-text">
                                {% if libro.resumen %}
                                    {{ libro.resumen|truncatewords:22 }}
                                {% else %}
                                    {% lorem 20 w random %}.
                                {% endif %}
                            </p>
                            <a class="btn btn-primary"
                               href="{{ libro.get_absolute_url }}"
                               role="button">Ver libro &#187</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/author_edit_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Editar Autor
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 my-5">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success">Actualizar Autor</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/author_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Lista de Libros
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="my-5">Lista de autores</h2>
            </div>
        </div>
        <div class="row">
            {% if autores.count == 0 %}
                <h3>Todavia no se han cargado autores.</h3>
            {% else %}
                {% for autor in autores %}
                    <div class="col-md-4">
                        <div class="card my-3">
                            <div class="card-body">
                                <h5 class="card-title">{{ autor.fullname }}</h5>
                                <p class="card-text">{% lorem 20 w random %}.</p>
                                <a class="btn btn-primary"
                                   href="{{ autor.get_absolute_url }}"
                                   role="button">Ver autor &#187</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/book_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Eliminar libro
{% endblock title %}
{% block content %}
    <div class="container mt-5">
        <form method="post">{% csrf_token %}
            <h1>Estas seguro de eliminar el libro: "{{ libro }}"?</h1>
            <a href="{% url 'libreria:book-crud' %}" class="btn btn-primary">Cancelar</a>
            <button type="submit" class="btn btn-danger">Eliminar Libro</button>
         </form>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/book_create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Agregar Libro
{% endblock title %}
{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-md-8 my-3">
                <h3 class="mb-3">Agregar libro</h3>
                {% if user.is_superuser %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-success">Agregar Libro</button>
                        <a href="{% url 'libreria:book-crud' %}" class="btn btn-primary">Cancelar</a>
                    </form>
                {% else %}
                    <h2>No tienes permisos suficientes para ingresar a esta sección.</h2>
                    <a href="{% url 'libreria:book-list' %}" class="btn btn-primary">Volver</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/book_crud.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Lista de Libros
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <div class="row">
            <div class="col">
                <h1>Lista de libros</h1>
                {% if user.is_superuser %}
                    <div class="btn-group" role="group" aria-label="links">
                        <a href="{% url 'libreria:create' %}"
                           type="button"
                           class="btn btn-secondary">Agregar libro</a>
                    </div>
                {% endif %}
                <table class="table table-hover mt-3">
                    <thead>
                        <tr>
                            <th scope="col">#ID</th>
                            <th scope="col">Título</th>
                            <th scope="col">Editorial</th>
                            <th scope="col">ISBN</th>
                            <th scope="col">Precio</th>
                            <th scope="col">Autor</th>
                            <th scope="col">Géneros</th>
                            <th scope="col">Tapa</th>
                            <th scope="col" colspan="2" class="text-center">Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for libro in libros %}
                            <tr>
                                <th scope="row">{{ libro.id }}</th>
                                <td>
                                    <a href="{% url 'libreria:book-detail' pk=libro.pk %}">{{ libro.title|title }}</a>
                                </td>
                                <td>{{ libro.editorial }}</td>
                                <td>{{ libro.isbn }}</td>
                                <td>{{ libro.price }}</td>
                                <td>{{ libro.author.fullname }}</td>
                                <td>
                                    {% for genero in libro.genre.all %}<span class="badge badge-pill badge-primary mx-1">{{ genero }}</span>{% endfor %}
                                </td>
                                <td>
                                    <img src="{{ libro.image.url }}"
                                         alt="{{ libro.title }}"
                                         width="30%"
                                         height="30%"/>
                                </td>
                                <td>
                                    {% if user.is_staff %}
                                        <a href="{% url 'libreria:book-update' pk=libro.pk %}"
                                           class="btn btn-warning">Editar</a>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if user.is_superuser %}
                                        <a href="{% url 'libreria:book-delete' pk=libro.pk %}"
                                           class="btn btn-danger">Eliminar</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/book_detail.html
{% extends "base.html" %}
{% block title %}
    {{ libro.title }}
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="card my-5 w-auto">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{ libro.image.url }}"
                         alt="{{ libro.title }}"
                         width="auto"
                         height="450px"/>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ libro.title }}</h5>
                        <p class="card-text">Precio: ${{ libro.price }}</p>
                        {% for genero in libro.genre.all %}
                            <a href="{% url 'libreria:genre-detail' pk=genero.pk %}"><span class="badge badge-pill badge-primary mx-1">{{ genero }}</span></a>
                        {% endfor %}
                        <p class="card-text">
                            {% if libro.resumen %}
                                {{ libro.resumen }}
                            {% else %}
                                {% lorem 200 w random %}.
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/book_edit_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Editar Libro
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 my-5">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success">Actualizar Libro</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/book_list.html
{% extends "base.html" %}
{% block title %}
    Lista de Libros
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            {% if libros.count == 0 %}
                <div class="d-block bg-info h-auto my-5">
                    <h2>No se han ingresado libros.</h2>
                </div>
            {% endif %}
            {% for libro in libros %}
                <div class="col-md-4">
                    <div class="card my-3">
                        <img src="{{ libro.image.url }}"
                             class="card-img-top"
                             alt="{{ libro.title }}"
                             height="400px"
                             width="auto"/>
                        <div class="card-body">
                            <h5 class="card-title">{{ libro.title }}</h5>
                            <h6 class="card-text">{{ libro.author }}</h6>
                            <p class="card-text">$ {{ libro.price }}</p>
                            <a class="btn btn-primary btn-block"
                               href="{{ libro.get_absolute_url }}"
                               role="button">Ver libro &#187</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/genre_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Eliminar género
{% endblock title %}
{% block content %}
    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            <h1>Estas seguro de eliminar al género: "{{ genero }}"?</h1>
            <a href="{% url 'libreria:genre-crud' %}" class="btn btn-primary">Cancelar</a>
            <button type="submit" class="btn btn-danger">Eliminar Género</button>
        </form>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/genre_detail.html
{% extends "base.html" %}
{% block title %}
    {{ genero }}
{% endblock title %}
{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-md-12">
                <h2>Listado de libros del género: {{ genero }}</h2>
                <p class="text-info">Cantidad de libros: {{ cantidad }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <h3>
                    {% if aviso %}{{ aviso }}{% endif %}
                </h3>
            </div>
        </div>
        <div class="row">
            {% for libro in libros %}
                <div class="col-md-4">
                    <div class="card my-3">
                        <img src="{{ libro.image.url }}"
                             class="card-img-top"
                             alt="{{ libro.title }}"
                             height="400px"
                             width="auto"/>
                        <div class="card-body">
                            <h5 class="card-title">{{ libro.title }}</h5>
                            <h6 class="card-text">{{ libro.author }}</h6>
                            <p class="card-text">
                                {% if libro.resumen %}
                                    {{ libro.resumen|truncatewords:22 }}
                                {% else %}
                                    {% lorem 20 w random %}.
                                {% endif %}
                            </p>
                            <a class="btn btn-primary"
                               href="{{ libro.get_absolute_url }}"
                               role="button">Ver libro &#187</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

apps/libreria/templates/libreria/genre_edit_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Editar Género
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 my-5">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success">Actualizar Género</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}