apps/libreria/urls.py
from django.urls import path
from .views import (
    BookListView,
    BookDetailView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
    BookCrudListView,
    AuthorListView,
    AuthorCreateView,
    AuthorUpdateView,
    AuthorDeleteView,
    AuthorCrudListView,
    author_detail,
    GenreCreateView,
    genero_detail,
    GenreUpdateView,
    GenreDeleteView,
    GenreCrudListView,
    search_books,
)

app_name = "libreria"

urlpatterns = [
    # URLs libros
    path("", BookListView.as_view(), name="book-list"),
    path("create/", BookCreateView.as_view(), name="create"),
    path("<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("<int:pk>/edit/", BookUpdateView.as_view(), name="book-update"),
    path("<int:pk>/delete/", BookDeleteView.as_view(), name="book-delete"),
    path("crud/", BookCrudListView.as_view(), name="book-crud"),
    path("search/", search_books, name="search-book"),
    # URLs autores
    path("author/", AuthorListView.as_view(), name="author-list"),
    path("author/create/", AuthorCreateView.as_view(), name="author-create"),
    path("author/<int:pk>/", author_detail, name="author-detail"),
    path("author/<int:pk>/edit/", AuthorUpdateView.as_view(), name="author-update"),
    path("author/<int:pk>/delete/", AuthorDeleteView.as_view(), name="author-delete"),
    path("author/crud/", AuthorCrudListView.as_view(), name="author-crud"),
    # URLs generos
    path("genre/create/", GenreCreateView.as_view(), name="genre-create"),
    path("genre/<int:pk>/", genero_detail, name="genre-detail"),
    path("genre/<int:pk>/edit/", GenreUpdateView.as_view(), name="genre-update"),
    path("genre/<int:pk>/delete/", GenreDeleteView.as_view(), name="genre-delete"),
    path("genre/crud/", GenreCrudListView.as_view(), name="genre-crud"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.libreria.views import home, AboutView

urlpatterns = (
    [
        # Django admin
        path("admin/", admin.site.urls),
        # Usuarios
        path("accounts/", include("django.contrib.auth.urls")),
        # Apps locales
        path("accounts/", include("apps.accounts.urls")),
        path("", home, name="index"),
        path("books/", include("apps.libreria.urls")),
        path("about/", AboutView.as_view(), name="about"),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

templates/about.html
{% extends "base.html" %}
{% block title %}
    About
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 my-5">
                <h1>About Page</h1>
                <p>Soy Damian Fratesi, y estoy estudiando programacion porque quiero cambiar ciertas cosas en la parte de la administracion de mi trabajo, que está basada en Excel.</p>
            </div>
        </div>
    </div>
{% endblock content %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="es-ar">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <meta name="keywords" content="libreria, libros" />
        <meta name="description" content="Libreria online" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
              integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
              crossorigin="anonymous"/>
        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    </head>
    <body class="bg-body">
        {% block navbar %}
            {% include "navbar.html" %}
        {% endblock navbar %}
        {% block content %}
        {% endblock content %}
        {% block footer %}
            {% include "footer.html" %}
        {% endblock footer %}
        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
        <!-- Font Awesome -->
        <script src="https://kit.fontawesome.com/98f1f4fe0e.js" crossorigin="anonymous"></script>
    </body>
</html>

templates/footer.html
<footer class="bg-light position-sticky">
  <div class="container py-3">
    <div class="row py-3">
      <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4">Nosotros</h6>
        <ul class="list-unstyled mb-0">
          <li class="mb-2">
            <a href="{% url 'about' %}" class="text-muted">Acerca de nosotros</a>
          </li>
          <li class="mb-2">
            <span class="text-muted">Email:</span>
            <a href="mailto:info@libreriatrelew.com" class="text-muted">info@libreriatrelew.com</a>
          </li>
          <li class="mb-2">
            <span class="text-muted">Telefono: </span>
            <a href="tel:+545555554848" class="text-muted">+54(555)555-4848</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4">Libreria</h6>
        <ul class="list-unstyled mb-0">
          <li class="mb-2">
            <a href="{% url 'login' %}" class="text-muted">Login</a>
          </li>
          <li class="mb-2">
            <a href="{% url 'signup' %}" class="text-muted">Registro</a>
          </li>
          <li class="mb-2">
            <a href="{% url 'libreria:book-list' %}" class="text-muted">Nuestros libros</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-4 col-md-6 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4">Nuestras Oficinas</h6>
        <p class="text-muted mb-4">Trelew, Chubut, Argentina</p>
        <ul class="list-inline mt-4">
          <li class="list-inline-item">
            <a href="https://twitter.com/dfratesi" target="_blank" title="twitter"><i class="fab  fa-2x fa-twitter"></i></a>
          </li>
          <li class="list-inline-item">
            <a href="https://www.instagram.com/dfratesi/"
               target="_blank"
               title="instagram"><i class="fab fa-2x fa-instagram"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <hr class="p-0 m-0 b-0" />
  <div class="bg-light py-2">
    <div class="container text-center">
      <p class="text-muted mb-0 py-2">&#169 2022 Libreria Trelew.</p>
    </div>
  </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% block title %}
    Libreria online
{% endblock title %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Libreria Trelew</h1>
            <p>{% lorem 25 w random %}.</p>
            <p>
                <a class="btn btn-primary btn-lg"
                   href="{% url 'libreria:book-list' %}"
                   role="button">Libros &#187</a>
            </p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col mb-3">
                <h2 align="center">
                    Últimos <span class="text-danger">ingresos</span>
                </h2>
            </div>
        </div>
        <div class="row mb-5">
            {% if libros.count == 0 %}
                <h2>Todavia no se han ingresado libros.</h2>
            {% else %}
                {% for libro in libros %}
                    <div class="col-md-4">
                        <h3>{{ libro.title|title }}</h3>
                        <h5>{{ libro.autor }}</h5>
                        <p>
                            {% if libro.resumen %}
                                {{ libro.resumen|truncatewords:30 }}
                            {% else %}
                                {% lorem 30 w random %}.
                            {% endif %}
                        </p>
                        <p>
                            <a class="btn btn-secondary"
                               href="{% url 'libreria:book-detail' pk=libro.pk %}"
                               role="button">Ver detalles &#187</a>
                        </p>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <!--/container-->
{% endblock content %}

templates/navbar.html
{% load static %}
{% url 'index' as index %}
{% url 'libreria:book-list' as books %}
{% url 'libreria:author-list' as author %}
{% url 'libreria:genre-list' as genre %}
{% url 'about' as about %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}">Libreria Trelew</a>
  <button class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item {% if request.path == books %}active{% endif %}">
        <a class="nav-link" href="{% url 'libreria:book-list' %}">
          <i class="fa-solid fa-book text-white-50"></i> Libros
          {% if request.path == books %}<span class="sr-only">(current)</span>{% endif %}
        </a>
      </li>
      <li class="nav-item {% if request.path == author %}active{% endif %}">
        <a class="nav-link" href="{% url 'libreria:author-list' %}">
          Autores
          {% if request.path == books %}<span class="sr-only">(current)</span>{% endif %}
        </a>
      </li>
      <li class="nav-item {% if request.path == about %}active{% endif %}">
        <a class="nav-link" href="{% url 'about' %}">
          Acerca de
          {% if request.path == about %}<span class="sr-only">(current)</span>{% endif %}
        </a>
      </li>
      {% if user.is_superuser or user.is_staff %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
             href="#"
             role="button"
             data-toggle="dropdown"
             aria-expanded="false">
            Administración
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'libreria:book-crud' %}">CRUD Libros</a>
            <a class="dropdown-item" href="{% url 'libreria:author-crud' %}">CRUD Autores</a>
            <a class="dropdown-item" href="{% url 'libreria:genre-crud' %}">CRUD Géneros</a>
            {% if user.is_superuser %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'admin:index' %}"><i class="fa fa-folder text-black-50" aria-hidden="true"></i> Admin Site</a>
            {% endif %}
          </div>
        </li>
      {% endif %}
      {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
             href="#"
             role="button"
             data-toggle="dropdown"
             aria-expanded="false">
            {% if user.profile.image %}
              <img src="{{ user.profile.image.url }}"
                   alt="{{ user.username }}"
                   width="auto"
                   height="22px"
                   class="rounded-circle"/>
            {% else %}
              <img src="{% static 'images/blank-profile-picture.png' %}"
                   alt="Sin imagen"
                   width="auto"
                   height="22px"
                   class="rounded-circle"/>
            {% endif %}
            {{ user.username }}
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ user.profile.get_absolute_url }}"><i class="fa fa-user text-black-50 mr-2" aria-hidden="true"></i> Ver perfil</a>
            <a class="dropdown-item"
               href="{% url 'edit-profile' %}"><i class="fa-solid fa-user-pen text-black-50"></i> Editar perfil</a>
            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa-solid fa-arrow-right-from-bracket text-black-50"></i> Log Out</a>
          </div>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Registrarse</a>
        </li>
      {% endif %}
    </ul>
  </div>
  <form class="form-inline"
        action="{% url 'libreria:search-book' %}"
        method="get">
    <input class="form-control mr-sm-2"
           type="search"
           name="search"
           placeholder="Buscar"
           aria-label="Search"/>
    <button class="btn btn-success my-2 my-sm-0" type="submit">Buscar</button>
  </form>
</nav>